apiVersion: v1
kind: Service
metadata:
  name: client
spec:
  type: ClusterIP
  selector:
    app: client
  ports:
    - name: "5400"
      protocol: TCP
      port: 5400
      targetPort: 5400
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  labels:
    app: client
spec:
  selector:
    matchLabels:
      app: client
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: client:latest
          imagePullPolicy: Never
          command:
            - bash
          args:
            - -c
            - "tail -f /dev/null"
          ports:
            - containerPort: 5400
